# ~/.config/starship.toml

# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# kuberenetes formatting
#format = """
#$all$newline$kubernetes
#$character"""

format = """$all$conda$character"""

# Inserts a blank line between shell prompts
add_newline = false

#[kubernetes]
#symbol = "⛵"
#format = "$symbol on [$context]($style)[([:](bold)$namespace)]($style) "
#style = "cyan italic"
#disabled = false

# ~/.config/starship.toml
[conda]
disabled = false
format = '[$symbol on $environment ]()'

[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[gcloud]
disabled = true

[docker_context]
disabled = false

[buf]
disabled = true
